### PR TITLE
Ad2017 Analfabet

### PR DESCRIPTION
**Pull request by xAndrei166**

### CODE REVIEW

**Review by ad2017gd — COMMENTED** [review]
dfdgdfg

**Comment by xAndrei166** [comment]
english be like

**Comment by CodingRule** [comment]
btw

**Comment by CodingRule** [comment]
xAndrei e analfabet

era corect sa mor eu "Use 'an' when the noun or adjective that comes next begins with a vowel sound"
This is an **one-time** prompt, only visible if there is no config file present. You can always toggle it under the system tray menu. If you change the location of the executable, make sure to **toggle the option in the menu**, and set it back on.

**Comment by xAndrei166** [comment]
daca te iei dupa teorie, da asa este, dar e mult mai usor sa pronunti "a
one time prompt" decat "an one time prompt"
adica suna mai bine

În dum., 31 dec. 2023 la 10:55, CodingRule ***@***.***> a
scris:

**Comment by CodingRule** [comment]
da stiu ca suna bine da totusi scriem corect

**Comment by CodingRule** [comment]
anyway era acu 4 ani asta Lol

**Comment by CodingRule** [comment]
scz 3

**Comment by ad2017gd** [comment]
CodingRule e analfabet( si mai si imprastie misinformation)

sa mor eu ca nu era corect "A one, because a is used before vowel sounding countable nouns, here one starts with a consonant sound w of when. A one is correct. Even though the word begins with 'o ' its pronunciation is consonantal i.e. with ' w ' so a will be used before it.

Plm

**Pull request merged**
